new_song_comment:
  path: /api/comments/songs/new
  methods: POST
  controller: App\Modules\Comments\UI\Http\Api\NewSongCommentAction
  options:
    middleware:
      - 'App\Common\Infrastructure\Middleware\NeedAuth'

get_song_comments:
  path: /api/comments/songs/{song_id}
  methods: GET
  controller: App\Modules\Comments\UI\Http\Api\GetSongCommentsAction
