new_song_comment:
  path: /api/comments/song/new
  methods: POST
  controller: App\Modules\Comments\Infrastructure\UI\Http\Api\NewSongCommentAction

get_song_comments:
  path: /api/comments/song/{song_id}
  methods: GET
  controller: App\Modules\Comments\Infrastructure\UI\Http\Api\GetSongCommentsAction
