services:
  _defaults:
    autowire: true
    public: false

  _instanceof:
    App\Modules\Comments\Domain\DomainEventSubscriber:
      tags: [ 'domain.event.subscriber' ]

  App\Modules\Comments\:
    resource: '../../../src/Modules/Comments/'

  App\Modules\Comments\Application\Authors\CreateAuthor\CreateAuthorHandler:
    tags: [ messenger.message_handler ]

  App\Modules\Comments\Application\Songs\CreateNewSong\CreateNewSongHandler:
    tags: [ messenger.message_handler ]

  App\Modules\Comments\Application\Songs\CreateNewComment\CreateNewSongCommentHandler:
    tags: [ messenger.message_handler ]

  App\Modules\Comments\Application\Songs\GetComments\GetCommentsHandler:
    tags: [ messenger.message_handler ]

  App\Modules\Comments\Application\Songs\GetComment\GetCommentHandler:
    tags: [ messenger.message_handler ]

  App\Modules\Comments\Domain\Authors\AuthorRepository:
    class: App\Modules\Comments\Infrastructure\Domain\Authors\DoctrineAuthorRepository

  App\Modules\Comments\Domain\Songs\SongRepository:
    class: App\Modules\Comments\Infrastructure\Domain\Songs\DoctrineSongRepository

  App\Modules\Comments\Domain\Songs\CommentRepository:
    class: App\Modules\Comments\Infrastructure\Domain\Songs\DoctrineCommentRepository

  App\Modules\Comments\Infrastructure\UI\Http\Api\:
    resource: '../../../src/Modules/Comments/Infrastructure/UI/Http/Api/'
    tags: [ 'controller.service_arguments' ]