services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Web\MVC\:
    resource: '../../../src/Web/MVC/'

  App\Web\MVC\Action\:
    resource: '../../../src/Web/MVC/Action/'
    tags: [ 'controller.service_arguments' ]