App\Modules\Accounts\Domain\Users\User:
  type: entity
  id:
    id:
      column: id
      type: UserId
  table: users
  repositoryClass: App\Modules\Accounts\Infrastructure\Domain\Users\DoctrineUserRepository
  fields:
    email:
      type: string
      nullable: false
      unique: true
    password:
      type: string
      nullable: false
    username:
      type: string
      nullable: false
    accessToken:
      type: string
      column: access_token
      nullable: true
    accessTokenExpiryAt:
      type: datetime_immutable
      column: access_token_expiry_at
      nullable: true
    createdAt:
      type: datetime_immutable
      column: created_at
      nullable: false
