doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        types:
            Accounts_UserId: App\Modules\Accounts\Infrastructure\Persistence\Doctrine\Mapping\Users\UserIdType
            Accounts_RoleId: App\Modules\Accounts\Infrastructure\Persistence\Doctrine\Mapping\Users\RoleIdType

            GenreId: App\Modules\SongsCatalog\Infrastructure\Persistence\Doctrine\Mapping\Genres\GenreIdType
            SongId: App\Modules\SongsCatalog\Infrastructure\Persistence\Doctrine\Mapping\Songs\SongIdType
            SongsCatalog_ArtistId: App\Modules\SongsCatalog\Infrastructure\Persistence\Doctrine\Mapping\Artists\ArtistIdType
            SongsCatalog_CreatorId: App\Modules\SongsCatalog\Infrastructure\Persistence\Doctrine\Mapping\Creators\CreatorIdType

            Comments_AuthorId: App\Modules\Comments\Infrastructure\Persistence\Doctrine\Mapping\Authors\AuthorIdType
            Comments_SongId: App\Modules\Comments\Infrastructure\Persistence\Doctrine\Mapping\Songs\SongIdType
            Comments_SongCommentId: App\Modules\Comments\Infrastructure\Persistence\Doctrine\Mapping\Songs\CommentIdType

            SongsReviews_GenreId: App\Modules\SongsReviews\Infrastructure\Persistence\Doctrine\Mapping\Genres\GenreIdType
            SongsReviews_ReviewId: App\Modules\SongsReviews\Infrastructure\Persistence\Doctrine\Mapping\Reviews\ReviewIdType
            SongsReviews_ArtistId: App\Modules\SongsReviews\Infrastructure\Persistence\Doctrine\Mapping\Artists\ArtistIdType
            SongsReviews_CreatorId: App\Modules\SongsReviews\Infrastructure\Persistence\Doctrine\Mapping\Creators\CreatorIdType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Accounts_Users:
                type: xml
                prefix: 'App\Modules\Accounts\Domain\Users'
                dir: '%kernel.project_dir%/src/Modules/Accounts/Infrastructure/Persistence/Doctrine/Mapping/Users'
                is_bundle: false
            SongsCatalog_Artists:
                type: xml
                prefix: 'App\Modules\SongsCatalog\Domain\Artists'
                dir: '%kernel.project_dir%/src/Modules/SongsCatalog/Infrastructure/Persistence/Doctrine/Mapping/Artists'
                is_bundle: false
            SongsCatalog_Genres:
                type: xml
                prefix: 'App\Modules\SongsCatalog\Domain\Genres'
                dir: '%kernel.project_dir%/src/Modules/SongsCatalog/Infrastructure/Persistence/Doctrine/Mapping/Genres'
                is_bundle: false
            SongsCatalog_Songs:
                type: xml
                prefix: 'App\Modules\SongsCatalog\Domain\Songs'
                dir: '%kernel.project_dir%/src/Modules/SongsCatalog/Infrastructure/Persistence/Doctrine/Mapping/Songs'
                is_bundle: false
            SongsCatalog_Creators:
                type: xml
                prefix: 'App\Modules\SongsCatalog\Domain\Creators'
                dir: '%kernel.project_dir%/src/Modules/SongsCatalog/Infrastructure/Persistence/Doctrine/Mapping/Creators'
                is_bundle: false
            SongsReviews_Artists:
                type: xml
                prefix: 'App\Modules\SongsReviews\Domain\Artists'
                dir: '%kernel.project_dir%/src/Modules/SongsReviews/Infrastructure/Persistence/Doctrine/Mapping/Artists'
                is_bundle: false
            SongsReviews_Genres:
                type: xml
                prefix: 'App\Modules\SongsReviews\Domain\Genres'
                dir: '%kernel.project_dir%/src/Modules/SongsReviews/Infrastructure/Persistence/Doctrine/Mapping/Genres'
                is_bundle: false
            SongsReviews_Reviews:
                type: xml
                prefix: 'App\Modules\SongsReviews\Domain\Reviews'
                dir: '%kernel.project_dir%/src/Modules/SongsReviews/Infrastructure/Persistence/Doctrine/Mapping/Reviews'
                is_bundle: false
            SongsReviews_Creators:
                type: xml
                prefix: 'App\Modules\SongsReviews\Domain\Creators'
                dir: '%kernel.project_dir%/src/Modules/SongsReviews/Infrastructure/Persistence/Doctrine/Mapping/Creators'
                is_bundle: false
            Comments_Authors:
                type: xml
                prefix: 'App\Modules\Comments\Domain\Authors'
                dir: '%kernel.project_dir%/src/Modules/Comments/Infrastructure/Persistence/Doctrine/Mapping/Authors'
                is_bundle: false
            Comments_Songs:
                type: xml
                prefix: 'App\Modules\Comments\Domain\Songs'
                dir: '%kernel.project_dir%/src/Modules/Comments/Infrastructure/Persistence/Doctrine/Mapping/Songs'
                is_bundle: false
