doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
        types:
            UserId: App\Modules\Accounts\Infrastructure\Persistence\Doctrine\Mapping\UserIdType
            GenreId: App\Modules\SongsCatalog\Infrastructure\Persistence\Doctrine\Mapping\Genres\GenreIdType
            SongId: App\Modules\SongsCatalog\Infrastructure\Persistence\Doctrine\Mapping\Songs\SongIdType
            SongsCatalog_ArtistId: App\Modules\SongsCatalog\Infrastructure\Persistence\Doctrine\Mapping\Artists\ArtistIdType
            SongsCatalog_CreatorId: App\Modules\SongsCatalog\Infrastructure\Persistence\Doctrine\Mapping\Creators\CreatorIdType
            #Comments_UserId: App\Modules\SongsCatalog\Infrastructure\Persistence\Doctrine\Mapping\Users\UserIdType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Accounts_Users:
                type: xml
                prefix: 'App\Modules\Accounts\Domain\Users'
                dir: '%kernel.project_dir%/src/Modules/Accounts/Infrastructure/Persistence/Doctrine/Mapping'
                is_bundle: false
            SongsCatalog_Artists:
                type: xml
                prefix: 'App\Modules\SongsCatalog\Domain\Artists'
                dir: '%kernel.project_dir%/src/Modules/SongsCatalog/Infrastructure/Persistence/Doctrine/Mapping/Artists'
                is_bundle: false
            SongsCatalog_Genres:
                type: xml
                prefix: 'App\Modules\SongsCatalog\Domain\Genres'
                dir: '%kernel.project_dir%/src/Modules/SongsCatalog/Infrastructure/Persistence/Doctrine/Mapping/Genres'
                is_bundle: false
            SongsCatalog_Songs:
                type: xml
                prefix: 'App\Modules\SongsCatalog\Domain\Songs'
                dir: '%kernel.project_dir%/src/Modules/SongsCatalog/Infrastructure/Persistence/Doctrine/Mapping/Songs'
                is_bundle: false
            SongsCatalog_Creators:
                type: xml
                prefix: 'App\Modules\SongsCatalog\Domain\Creators'
                dir: '%kernel.project_dir%/src/Modules/SongsCatalog/Infrastructure/Persistence/Doctrine/Mapping/Creators'
                is_bundle: false
            #Comments_Users:
            #    type: xml
            #    prefix: 'App\Modules\Comments\Domain\Users'
            #    dir: '%kernel.project_dir%/src/Modules/Comments/Infrastructure/Persistence/Doctrine/Mapping/Users'
            #    is_bundle: false
