get_new_songs_today:
  path: /api/songs-catalog/songs/new-today
  methods: GET
  controller: App\Modules\SongsCatalog\UI\Http\Api\GetNewSongsTodayAction
  options:
    middleware:
      - 'App\Common\Infrastructure\Middleware\NeedAuth'