home_page:
  path: /
  methods: GET
  controller: App\Web\ADR\Action\HomePageAction

sign_in_page:
  path: /sign-in
  methods: GET
  controller: App\Web\ADR\Action\Accounts\SignInPageAction

sign_in:
  path: /sign-in
  methods: POST
  controller: App\Web\ADR\Action\Accounts\SignInAction

register_page:
  path: /register
  methods: GET
  controller: App\Web\ADR\Action\Accounts\RegisterPageAction

register:
  path: /register
  methods: POST
  controller: App\Web\ADR\Action\Accounts\RegisterAction

logout:
  path: /logout
  methods: GET
  controller: App\Web\ADR\Action\Accounts\LogoutAction

new_song:
  path: /songs/new
  methods: GET
  controller: App\Web\ADR\Action\SongsCatalog\NewSongPageAction