services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Web\ADR\:
    resource: '../../../src/Web/ADR/'

  App\Web\ADR\Action\:
    resource: '../../../src/Web/ADR/Action/'
    tags: [ 'controller.service_arguments' ]