version: '3'
services:
  web:
    container_name: allchords_php
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "${WEB_PORT}:8080"
    environment:
      PHP_XDEBUG_REMOTE_PORT: "${PHP_XDEBUG_REMOTE_PORT}"
      PHP_XDEBUG_REMOTE_HOST: "${PHP_XDEBUG_REMOTE_HOST}"
    volumes:
      - ../:/app
  db:
    container_name: allchords_mysql
    image: "mysql:8"
    expose:
      - "3306"
    ports:
      - "${DATABASE_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
