accounts:
  resource: 'modules/accounts/routes.yaml'

comments:
  resource: 'modules/comments/routes.yaml'

songs_catalog:
  resource: 'modules/songs_catalog/routes.yaml'

songs_reviews:
  resource: 'modules/songs_reviews/routes.yaml'
