#index:
#    path: /
#    controller: App\Controller\DefaultController::index

accounts:
  resource: 'modules/accounts/routes.yaml'

songs_catalog:
  resource: 'modules/songs_catalog/routes.yaml'

comments:
  resource: 'modules/comments/routes.yaml'
