#index:
#    path: /
#    controller: App\Controller\DefaultController::index

songs_catalog:
  resource: 'modules/songs_catalog/routes.yaml'

comments:
  resource: 'modules/comments/routes.yaml'

web_adr:
  resource: 'web/adr/routes.yaml'
