parameters:
    database_fixtures_sql: '%kernel.project_dir%/%env(DATABASE_FIXTURES_SQL)%'
    database_name: '%env(DATABASE_NAME)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Common\:
        resource: '../src/Common/'

imports:
    - { resource: 'modules/common/services.yaml' }
    - { resource: 'modules/accounts/services.yaml' }
    - { resource: 'modules/songs_catalog/services.yaml' }
    - { resource: 'modules/songs_reviews/services.yaml' }
    - { resource: 'modules/comments/services.yaml' }