register_user:
  path: /api/accounts/auth/register
  methods: POST
  controller: App\Modules\Accounts\UI\Http\Api\RegisterUserAction

sign_in_user:
  path: /api/accounts/auth/sign-in
  methods: POST
  controller: App\Modules\Accounts\UI\Http\Api\SignInUserAction

get_authenticated_user:
  path: /api/accounts/users/authenticated
  methods: GET
  controller: App\Modules\Accounts\UI\Http\Api\GetAuthenticatedUserAction
  options:
    middleware:
      - 'App\Common\Infrastructure\Middleware\NeedAuth'