services:
  _defaults:
    autowire: true
    public: false

  _instanceof:
    App\Modules\Accounts\Domain\DomainEventSubscriber:
      tags: ['domain.event.subscriber']

    App\Common\Application\Command\CommandHandler:
      tags:
        - { name: messenger.message_handler, bus: command.bus }
    App\Common\Application\Query\QueryHandler:
      tags:
        - { name: messenger.message_handler, bus: query.bus }
  
  App\Modules\Accounts\:
    resource: '../../../src/Modules/Accounts/'

  App\Modules\Accounts\UI\Http\Api\:
    resource: '../../../src/Modules/Accounts/UI/Http/Api/'
    tags: [ 'controller.service_arguments' ]