services:
  _defaults:
    autowire: true
    public: false

  _instanceof:
      App\Modules\Accounts\Domain\DomainEventSubscriber:
        tags: ['domain.event.subscriber']
  
  App\Modules\Accounts\:
    resource: '../../../src/Modules/Accounts/'

  App\Modules\Accounts\Domain\Users\UserRepository:
    class: App\Modules\Accounts\Infrastructure\Domain\Users\DoctrineUserRepository

  App\Modules\Accounts\Application\Users\RegisterUser\RegisterUserHandler:
    tags: [messenger.message_handler]

  App\Modules\Accounts\Application\Users\SignInUser\SignInUserHandler:
    tags: [messenger.message_handler]

  App\Modules\Accounts\Application\Users\GetToken\GetTokenHandler:
    tags: [messenger.message_handler]

  App\Modules\Accounts\Application\Users\GetUserByToken\GetUserByTokenHandler:
    tags: [messenger.message_handler]

  App\Modules\Accounts\Application\Users\GenerateNewToken\GenerateNewTokenHandler:
    tags: [messenger.message_handler]

  App\Modules\Accounts\Application\Users\GetUserPermissions\GetUserPermissionsHandler:
    tags: [messenger.message_handler]